# Generated by Django 4.0.1 on 2022-01-19 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='audio',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['mp3'], message='Файл должен быть расширения .mp3')], verbose_name='Введите файл расширения .mp3'),
        ),
    ]
